version: '3'
volumes:
  db_dev_vol:

networks:
  phpnet:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - phpnet

  mysql:
    image: mysql:5.6
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - db_dev_vol:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: supersecret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - phpnet

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - phpnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8001:80"
    links:
      - mysql:db
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_ROOT_HOST: "%"
      MYSQL_PASSWORD: secret
    networks:
      - phpnet

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - phpnet

  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - phpnet
    entrypoint: ['npm']

